#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

alias mkcd='mkdcd'
alias tlog='tail -f log/development.log'
alias git="noglob git"
alias bower='noglob bower'

function tloga {
  tail -f ~/Library/Logs/Pow/apps/$1.log
}

eval "$(rbenv init - --no-rehash zsh)"

function c {
  if (($+1)); then
    ~/Code/$1
  fi
  path=( ./bin $path )
}

_c() { _files -W ~/Code -/; }
compdef _c c

function rst {
  touch tmp/restart.txt
}
