#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

alias mkcd='mkdcd'
alias tlog='tail -f log/development.log'

function tloga {
  tail -f ~/Library/Logs/Pow/apps/$1.log
}

eval "$(rbenv init - --no-rehash zsh)"

c() { cd ~/Code/$1; }
_c() { _files -W ~/Code -/; }
compdef _c c
